version: "3"

includes:
  lint: ./scripts/lint.yml
  fmt: ./scripts/fmt.yml
  ci: ./scripts/ci.yml

tasks:
  cfg:scripts:
    run: once
    desc: Configure Scripts to be executable
    cmds:
      - chmod -R +x ./scripts
  admin:
    desc: Become Terraform user
    cmds:
      - ./scripts/become_terraform_user.sh

  init:all:
    desc: Run Terraform init on all folders
    cmds:
      - find . -type f -name '*.tf' -printf '%h\n' | uniq | xargs  -I {} sh -c 'echo Initializing {} ... && cd {} && terraform init'
  validate:all:
    desc: Run Terraform validate on all folders
    cmds:
      - find . -type f -name '*.tf' -printf '%h\n' | uniq | xargs  -I {} sh -c 'echo Validating {} ... && cd {} && terraform validate'

  #Build
  run:app:
    desc: Run the go program
    cmds:
      - go run . {{ .CLI_ARGS }}

  #Pre-commit
  gattai:doc:
    desc: Run gattai doc on gattai_actions
    cmds:
      - go run . document ./gattai_actions

  # Utility
  lint:
    desc: Run all linters
    cmds:
      - task: lint:sh
  fmt:
    desc: Run all formatters
    cmds:
      - task: fmt:sh
      - task: fmt:md
      - task: fmt:yaml
      - task: fmt:nix
