version: v1
type: CommandLineInterface
params:
  required:
    name:
      desc: The kube configmap name
      type: string
    namespace:
      desc: The kube configmap namespace
      type: string
  optional:
    fromFile:
      desc: Create kube configmap from file
      type: string
    fromEnvFile:
      desc: Create kube configmap from envfile
      type: string
    fromLiterals:
      desc: Create kube configmap from literals
      type: dict
      dict_of:
        key:
          type: string
        value:
          type: string

spec:
  runtime_env:
    nix_shell:
      kubectl:
        name: kubectl
        version: https://github.com/NixOS/nixpkgs/archive/bf972dc380f36a3bf83db052380e55f0eaa7dcb6.tar.gz
  exec:
    cmds:
      - command: kubectl
        {{- with .Vars }}
        args:
          - create configmap
          - {{ .name }}
          {{- range $key, $val := .fromLiterals }}
          - --from-literal={{ $key }}={{ $val }}
          {{- end }}
          {{- with .namespace }}
          - --namespace={{ . }}
          {{- end }}
          {{- with .fromFile }}
          - --from-file={{ . }}
          {{- end }}
          {{- with .fromEnvFile }}
          - --from-env-file={{ . }}
          {{- end }}
          - --dry-run=client -o yaml
        {{- end }}
