version: v1
type: CommandLineInterface
params:
  name:
    desc: The kube configmap name
    requied: true
    type: string
  namespace:
    desc: The kube configmap namespace
    requied: true
    type: string
  from-file:
    desc: Create kube configmap from file
    requied: false
    type: string
spec:
  test:
    - command: kubectl
      args:
        - get configmaps --all-namespaces
  cmds:
    - command: kubectl
      args:
        -  create configmap
        {{- with .Vars }}
        - {{ .name }}
        {{- range $key, $val := .from_literals }}
        - --from-literal={{ $key }}={{ $val }}
        {{- end }}
        {{- with .namespace }}
        - --namespace={{ . }}
        {{- end }}
        {{- with .from_file }}
        - --from-file={{ temp_folder .key }}
        {{- end }}
        {{- with .from_env_file }}
        - --from-env-file={{ temp_folder .key }}
        {{- end }}
        - --dry-run=client -o yaml
        {{- end }}
