version: v1
type: CommandLineInterface
params:
  name:
    desc: The kube secret name
    requied: true
    type: string
  namespace:
    desc: The kube secret namespace
    requied: true
    type: string
  from-file:
    desc: Create kube secret from file
    requied: false
    type: string
return: "stdout"
spec:
  test:
    - cmd:
      - kubectl get secrets --all-namespaces
  cmds:
    - cmd:
      - kubectl create secret generic
      {{- with .Args }}
      - {{ .name }}
      {{- range $key, $val := .from-literals }}
      - --from-literal={{ $key }}={{ $val }}
      {{- end }}
      {{- with .namespace }}
      - --namespace={{ . }}
      {{- end }}
      {{- with .from-file }}
      - --from-file={{ temp_folder .key }}
      {{- end }}
      {{- with .from-env-file }}
      - --from-env-file={{ temp_folder .key }}
      {{- end }}
      - -o yaml
      {{- end }}
