version: v1
type: CommandLineInterface
params:
  required:
    name:
      desc: The kube secret name
      type: string
    namespace:
      desc: The kube secret namespace
      type: string
  optional:
    from_file:
      desc: Create kube secret from file
      type: string
    from_env_file:
      desc: Create kube secret from envfile
      type: string
    from_literals:
      desc: Create kube secret from literals
      type: map
spec:
  test:
    - command: kubectl
      args:
        - get secrets --all-namespaces
  cmds:
    - command: kubectl
      args:
        - create secret generic
        {{- with .Vars }}
        - {{ .name }}
        {{- range $key, $val := .from_literals }}
        - --from-literal={{ $key }}={{ $val }}
        {{- end }}
        {{- with .namespace }}
        - --namespace={{ . }}
        {{- end }}
        {{- with .from_file }}
        - --from-file={{ . }}
        {{- end }}
        {{- with .from_env_file }}
        - --from-env-file={{ . }}
        {{- end }}
        - --dry-run=client -o yaml
        {{- end }}
